### ISSUE TITLE
Getting a Silent Token Response with the Username but no Access Token

### ISSUE THREAD

**Issue by MrFabou** [peted70/aad-hololens-mrtk3#1]
Hey!
Nice Work you've done here. 
I tried your sample but I'm getting no Access Token out of it.
What I done: 
deleted the Resource cause I don't want to auth against a webapi (for now), linked the Login Method to the Login Button and changed the ClientID to mine.

Silent Token Response: Success
Username = name@email.com
Access Token: 

That's what I get in the UnityPlayer Log.

Hope you can help :-) 

Greetings!

**Comment by MrFabou** [comment]
I saw that you need a resource in order to get a token back. I hope I can just change it to whatever I need. 
My bad :-)

**Comment by peted70** [comment]
Aha! Yeah, it is easy to miss something there - a lot of fiddly details.
